name: Teraform

on:
  # Triggers the workflow on push or pull request events but only for the "Main" branch
  push:
    branches: [ "Main", "feature/branch" ]


jjobs:
  # This workflow contains a single job called "build"
  terraform:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: "Install pre-reqs"
        run: |
          curl -SL "https://releases.hashicorp.com/terraform/1.0.8/terraform_1.0.8_linux_amd64.zip" --output terraform.xip
          unzip "terraform.zip"
          mv terraform /usr/local/bin
          terraform --version
          rm terraform.zip

      - name: "Install TFLINT"
        run: |
          wget https://github.com/terraform-linters/tflint/releases/download/v0.25.0/tflint_linux_amd64.zip
          unzip tflint_linux_amd64
          mv tflint /usr/local/bin